### ISSUE TITLE
 Error: This socket has been ended by the other party

### ISSUE THREAD

**Issue by IlhanSeven** [node-modbus/stream#13]
I am trying to run a tcp master app in a docker container. First time I run "docker-compose up" everything went well but after that all I am getting is this: 

Can you please help dresende?

```
 Error: This socket has been ended by the other party
     at Socket.writeAfterFIN [as write] (net.js:290:12)
     at Transport.BaseTransport.write (/C:\Users\Ilhan\Desktop\IcaxMaster/node_modules/modbus-stream/lib/transport/transport.js:46:15)
     at /C:\Users\Ilhan\Desktop\IcaxMaster/node_modules/modbus-stream/lib/transport/transport.js:80:13
     at call_queue (/C:\Users\Ilhan\Desktop\IcaxMaster/node_modules/modbus-stream/lib/transport/transport.js:190:38)
     at Transport.BaseTransport.retrySend (/C:\Users\Ilhan\Desktop\IcaxMaster/node_modules/modbus-stream/lib/transport/transport.js:79:2)
     at Transport.BaseTransport.send (/C:\Users\Ilhan\Desktop\IcaxMaster/node_modules/modbus-stream/lib/transport/transport.js:72:8)
     at Stream.writeMultipleRegisters (/C:\Users\Ilhan\Desktop\IcaxMaster/node_modules/modbus-stream/lib/stream.js:174:17)
     at Timeout._onTimeout (/C:\Users\Ilhan\Desktop\IcaxMaster/app.js:38:20)
     at ontimeout (timers.js:386:11)
     at tryOnTimeout (timers.js:250:5)
```

**Comment by dresende** [comment]
Post your tcp master code to see if I can spot anything.

**Comment by IlhanSeven** [comment]
```
function connectToSlave() {
	modbus.tcp.connect(modbusPort, modbusIp, { debug: null }, (err, connection) => {
    
		if(err) {
			//throw err;
			console.log("Will try to reconnect in 3 seconds");
			setTimeout(connectToSlave, 3000);
		} else {
			console.log("Connected to the slave");
			setInterval(function(){
				
				var valuesArray = new Array();
				for(var i = 42001; i <= 42017; i++) {
					
					valuesArray.push(gatewayMap[i]);
				}
				
				connection.writeMultipleRegisters({ address: 42001, values: valuesArray}, (err, info) => {
					
					if(err) throw err;
				});
				
				connection.readInputRegisters({ address: 42101, quantity: 7}, (err, res) => {
					
					if(err) throw err;
					for(var i = 0; i<7; i++) {
						gatewayMap[i+42101] = res.response.data[i];
					}
					io.emit('updateInputRegisters', { values: gatewayMap });
				})
				
				connection.readInputRegisters({ address: 49001, quantity: 6}, (err, res) => {
					
					if(err) throw err;
					for(var i = 0; i<6; i++) {
						gatewayMap[i+49001] = res.response.data[i];
					}
					io.emit('updateInputRegisters', { values: gatewayMap });
				})
				
			}, 1000);
		}
	});
}
```

**Comment by dresende** [comment]
I was not thinking properly, missing my coffee. Your initial error is not related to docker, it's telling you your other end closed the socket. Perhaps because you have a `setInterval` the connection is ended in the meanwhile and you keep requesting information but the socket stream is closed.

**Comment by dresende** [comment]
I'm also not sure if it's not a problem with `io`.

**Comment by IlhanSeven** [comment]
you might be right about setInterval. Do you have any suggestions or alternatives to it?

**Comment by dresende** [comment]
I would store the interval id. Something like this:

```js
let timer = setInterval(...);
```

And after that I would listen for the `error` event in the `connection` object and would stop the interval and reconnect.
