### ISSUE TITLE
Ending a Connection, Multiple Reading of Registers

### ISSUE THREAD

**Issue by pleubner** [node-modbus/stream#14]
Hi ,
I am new to modbus & node.js . Nevertheless I was able to read and write holding registers of a my-PV  Boiler Heater ( Model: ELWA-E ) .  This heater screw in heater has a LAN and modbus-tcp connection.

I am not sure why the node execution continues (does not end)  , and why a third communication fails.

The code below opens a connection, then reads all the holding registers,  sets the target boiler temperature , and finally re-reads the set register to validate the change.

I need to somehow close the connection ( timeout , timer ? .... )  , and be able to do the last "readHoldingRegisters". Any help would be appreciated.

Here is the code -

**Comment by pleubner** [comment]
/*
   MODBUS CONTROL : my-PV ELWA-E Heizstab
   
   The operation in the web admin insterface must be set to Modbus-TCP 
   All Registers are 16 bit unsigned integer

   Address r/w Parameter value unit
   ----------------------------------------------------------------
   1000 R/W Power W 
   1001 R   Actual Water Temp.  0,1°C 
   1002 R   Target Water Temp (Dial Adjustment on device ) 0,1 °C 
   1003 R   Status (See below) Number
   1004 R/W Control timeout  secs 
   1005 R/W Secure Warm water : mode  Number
   1006 R/W  Secure Warm water : temp.  °C 
   1007 R/W Secure Warm water : Start time (Hour)
   1008 R/W Secure Warm water : End time (Hour)
   1009 R/W CurrentTime (Hour)
   1010 R/W Current Time (Minute) 
   1011 R/W  Current Time (Seconds) 
   1012 W   Manual Start Heatingf  1 
   1013 R/W ELWA number AC ELWA Nummer; Default is 1 
   1014 R/W Fusetype 13 or 16 A; Default is 16A 
   1015 R   tempchip Controller Temp.
   1016 R   IP firmware version Software Version TCP Board
   1017 R   ELWA firmware version Software Version Powerunit
   1018 R   ELWA serial number 1-2 
   1019 R   ELWA serial number 3-4 
   1020 R   ELWA serial number 5-6 
   1021 R   ELWA serial number 7-8 
   1022 R   ELWA serial number 9-10 
   1023 R   ELWA serial number 11-12 
   1024 R   ELWA serial number 13-14 
   1025 R   ELWA serial number 15-16 
   1026 R/W 2nd. Secure Warm water : Start time (Hour)
   1027 R/W 2nd. Secure Warm water : End time (Hour)


Registers can be read via  Modbus command 0x06 or 0x16 

Status No.     Description
--------------------------------
2 Heat 
3 Standby 
4 Boost heat 
5 Heat finished 
9 Setup 

201 Error Overtemp Fuse blown 
202 Error Overtemp measured 
203 Error Overtemp Electronics 
204 Error Hardware Fault 
205 Error Temp Sensor

*/

//'use strict';

var modbus = require("modbus-stream");


modbus.tcp.connect(502,
    "192.168.2.140", { debug: null }, // { debug: "automaton-2454" },
    (err, connection) => {
        // do something with connection
        if (err) throw err;

        console.log("Connection established. Now requesting Data from the my-PV ELWA-E Heater");

        // Reading a single register value. Current Power Output. Start at address 1000 and only read 1 register
        /*
        connection.readHoldingRegisters({ address: 1000, quantity: 1 }, (err, res) => {
            if (err) throw err;
            console.log("Current Power Output (W): %s", res.response.data[0].readUInt16BE(0));
            console.log(res); // Prints all Data for register
        });
        */

        // read All Data (28 Registers) . The read starts at address 1000 and reads up to Address 1027
        connection.readHoldingRegisters({ address: 1000, quantity: 28 }, (err, res) => {
            if (err) throw err;

            console.log("Leistung                                                 : %dW", res.response.data[00].readUInt16BE(0));
            console.log("Wasser-Temperatur Ist                                    : %f°C", res.response.data[01].readUInt16BE(0) / 10);
            console.log("Wasser-Temperatur Ziel (am Drehknopf eingestellt)        : %f°C", res.response.data[02].readUInt16BE(0) / 10);
            console.log("Status (siehe unten) Zahl                                : %d", res.response.data[03].readUInt16BE(0));
            console.log("Zeitablauf Ansteuerung                                   : %d sek", res.response.data[04].readUInt16BE(0));
            console.log("Warmwassersicherstellungsmodus 1 Zahl                    : %d", res.response.data[05].readUInt16BE(0));
            console.log("Warmwassersicherstellungstemperatur                      : %d°C", res.response.data[06].readUInt16BE(0));
            console.log("Warmwassersicherstellung Startzeit/Endzeit (Stunde)      : %d / %d", res.response.data[07].readUInt16BE(0), res.response.data[08].readUInt16BE(0));
            console.log("aktuelle Uhrzeit                                         : %d:%d:%d", res.response.data[09].readUInt16BE(0), res.response.data[10].readUInt16BE(0), res.response.data[011].readUInt16BE(0));
            console.log("Manueller Start Nachladung 1                             : %d", res.response.data[12].readUInt16BE(0));
            console.log("ELWA number AC ELWA Nummer (Standard ist 1)              : %d", res.response.data[13].readUInt16BE(0));
            console.log("Fusetype 13 oder 16 A (Standard ist 16A)                 : %dA", res.response.data[14].readUInt16BE(0));
            console.log("tempchip Controller Temperatur                           : %d°C", res.response.data[15].readUInt16BE(0));
            console.log("IP firmware version Software Version TCP Platine         : %s", res.response.data[16].readUInt16BE(0));
            console.log("ELWA firmware version Software Version Leistungsteil     : %s", res.response.data[17].readUInt16BE(0));
            console.log("ELWA serial number                                       : %s:%s:%s:%s:%s:%s:%s:%s", res.response.data[18].readUInt16BE(0), res.response.data[19].readUInt16BE(0), res.response.data[20].readUInt16BE(0), res.response.data[21].readUInt16BE(0), res.response.data[22].readUInt16BE(0), res.response.data[23].readUInt16BE(0), res.response.data[24].readUInt16BE(0), res.response.data[25].readUInt16BE(0));
            console.log("2. Warmwassersicherstellung Startzeit/Endzeit (Stunde)   : %d / %d", res.response.data[26].readUInt16BE(0), res.response.data[27].readUInt16BE(0));
        });


        // Set new "Warmwassersicherstellungstemperatur" to 51°C , 51 (Decimal)  = 0033 (Hex)  
        connection.writeSingleRegister({ address: 1006, value: Buffer.from([0x00, 0x34]) });

        // Re-read register to show the change
        /*
        connection.readHoldingRegisters({ address: 1006, quantity: 1 }, (err, res) => {
            if (err) throw err;
            console.log("Warmwassersicherstellungstemperatur                      : %d°C", res.response.data[0].readUInt16BE(0));
        });
        */
    }
);

**Comment by pleubner** [comment]
I get the following after a timeout .....

```javascript
[Running] node "c:\Users\peter\code\modbus\modbus-tcp-01.js"
Connection established. Now requesting Data from the my-PV ELWA-E Heater
Leistung                                                 : 600W
Wasser-Temperatur Ist                                    : 51°C
Wasser-Temperatur Ziel (am Drehknopf eingestellt)        : 49.5°C
Status (siehe unten) Zahl                                : 4
Zeitablauf Ansteuerung                                   : 10 sek
Warmwassersicherstellungsmodus 1 Zahl                    : 2
Warmwassersicherstellungstemperatur                      : 52°C
Warmwassersicherstellung Startzeit/Endzeit (Stunde)      : 17 / 23
aktuelle Uhrzeit                                         : 3:0:3
Manueller Start Nachladung 1                             : 0
ELWA number AC ELWA Nummer (Standard ist 1)              : 1
Fusetype 13 oder 16 A (Standard ist 16A)                 : 16A
tempchip Controller Temperatur                           : 46°C
IP firmware version Software Version TCP Platine         : 101
ELWA firmware version Software Version Leistungsteil     : 106
ELWA serial number                                       : 12598:12337:12852:12599:12592:12345:12336:12345
2. Warmwassersicherstellung Startzeit/Endzeit (Stunde)   : 5 / 6
c:\Users\peter\node_modules\modbus-stream\lib\transport\transport.js:93
						return next(pdu.Exception.error("GatewayTargetDeviceFailedToRespond"));
						       ^

TypeError: next is not a function
    at Timeout._onTimeout (c:\Users\peter\node_modules\modbus-stream\lib\transport\transport.js:93:14)
    at ontimeout (timers.js:475:11)
    at tryOnTimeout (timers.js:310:5)
    at Timer.listOnTimeout (timers.js:270:5)

[Done] exited with code=1 in 31.181 seconds
```
