### ISSUE TITLE
Erreur after some times of execcuting sequential reading of coils 

### ISSUE THREAD

**Issue by Mohamedelhrichi** [node-modbus/stream#30]
hello my project of modbus-steam  it's reading some registers of my modbus tcp devices .

i use a Setinterval JS function to read every minute my devices  , but after  some times ( may be 1 or 2 hours or less ) my script stops with ECONNRESET  ERROR 

Question : Ho can i handlle this error  to  disable script stopp and continue reading or waiting until connection is OK

error is 

`Error: read ECONNRESET
    at TCP.onStreamRead (internal/stream_base_commons.js:111:27)
Emitted 'error' event at:
    at Transport.<anonymous> (D:\serveur\readmodbus\node_modules\modbus-stream\l
ib\stream.js:36:10)
    at Transport.emit (events.js:182:13)
    at Transport.<anonymous> (D:\serveur\readmodbus\node_modules\modbus-stream\l
ib\transport\transport.js:21:8)
    at Socket.emit (events.js:182:13)
    at emitErrorNT (internal/streams/destroy.js:82:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)
    at process._tickCallback (internal/process/next_tick.js:63:19)`

**Comment by dresende** [comment]
You should listen for the `error` event and reconnect. Alternatively, you could connect, read and close connection until you need to read again, unless you read a lot of addresses.
