### ISSUE TITLE
I don't get a response, but debug information

### ISSUE THREAD

**Issue by uNki23** [node-modbus/stream#40]
Hi!

I'm able to establish a connection to a Siemens S7 via Modbus TCP. 

I'm trying to read the holding registers. If I run the application I get the "Connected." info and the debug information that shows the data sent to the device. But I don't get the res object of the function call. I get a timeout instead:

````
Error while reading holding registers:  { Error: GatewayTargetDeviceFailedToRespond
    at Object.exports.error (/Users/uNki/Documents/Development/modbus_test/node_modules/modbus-pdu/lib/Exception.js:24:13)
    at Timeout._onTimeout (/Users/uNki/Documents/Development/modbus_test/node_modules/modbus-stream/lib/transport/transport.js:93:33)
    at ontimeout (timers.js:475:11)
    at tryOnTimeout (timers.js:310:5)
    at Timer.listOnTimeout (timers.js:270:5) code: 11 }
`````

here is my code:

````javascript
const modbus = require("modbus-stream");

modbus.tcp.connect(502, "192.168.0.1", { debug: "server" }, (err, connection) => {
    if (err)
        console.error('Connection error: ', err)

    console.log('Connected.\n')

    connection.readHoldingRegisters({ address: 0, quantity: 20, extra: { unitId: 1 } }, (err, res) => {
        if (err)
            return console.error('Error while reading holding registers: ', err)
        console.log('Response: ', res); // 
    })

    connection.on('error', err => {
        if (err.message != 'write EPIPE')
            console.log('Unknown error:', err.message)
    })
});
````

**Comment by dresende** [comment]
That's very weird, we communicate with S7 all the time. Have you tried debugging using another software to see what/how it responds?

**Comment by uNki23** [comment]
Sorry, error was on our end. Connection to the S7 was corrupted. This thing can be closed / deleted.

Awesome library! 👍
