### ISSUE TITLE
 Error: GatewayTargetDeviceFailedToRespond

### ISSUE THREAD

**Issue by sexbee** [node-modbus/stream#50]
receive data from TCP client : 

{ Error: GatewayTargetDeviceFailedToRespond
    at Object.exports.error (/Users/mac/Desktop/RLLP-PCL5new/node_modules/modbus-pdu/lib/Exception.js:24:13)
    at Timeout._onTimeout (/Users/mac/Desktop/RLLP-PCL5new/node_modules/modbus-stream/lib/transport/transport.js:92:33)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5) code: 11 }

I cant find cause?

**Comment by sexbee** [comment]
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: read ECONNRESET
    at TCP.onread (net.js:622:25)

**Comment by viatick** [comment]
![Screenshot 2019-11-17 at 5 00 35 PM](https://user-images.githubusercontent.com/20658463/69005340-df39c300-095b-11ea-9c0c-9f1cfcc54db4.png)


error : Error: GatewayTargetDeviceFailedToRespond
result : undefined

when reading at address 0?
